config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups do
    resources :entities
  end

  unauthenticated do
    root "splash_screen#index"
  end

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Group do |group|
      group.user_id == user.id
    end

    can :manage, Entity do |entity|
      entity.user_id == user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  # ApplicationRecord
end

app/models/entity.rb
class Entity < ApplicationRecord
  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :user
  has_many :groups
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true

  belongs_to :user
  has_many :group_entities
  has_many :entities, through: :group_entities

  def total_amount
    total = 0
    entities.each do |entity|
      total += entity.amount
    end
    total
  end
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :surname, presence: true

  has_many :entities
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:first_name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @group = Group.find(params[:group_id])
    @entities = @group.entities.order(created_at: :desc)

    redirect_to new_user_session_path, notice: 'You cannot access this resource.' if @group.user != current_user
  end

  def new
    @group = Group.find(params[:group_id])
    @groups = Group.where(user: current_user)
    @entity = Entity.new
  end

  def edit; end

  def create
    @entity = Entity.new(entity_params)
    @entity.user = current_user
    @group = Group.find(params[:group_id])
    @group.entities << @entity

    if @entity.save
      redirect_to group_entities_path(@group), notice: 'Your transaction has been added successfully!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, :user_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = Group.where(user: current_user)
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    if @group.save
      redirect_to groups_path, notice: 'Your new category has been created successfully!'
    else
      redirect_to new_group_path, notice: 'An error occured. Please try again.'
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:first_name, :surname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
  # EntitiesHelper
end

app/helpers/group_entities_helper.rb
module GroupEntitiesHelper
  # GroupEntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  # GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # UsersHelper
end

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<div class='new--cart'>
  <div class='btn--div'>
    <div class='arrow--back'><%= link_to "<", groups_path, class: "btn btn-secondary btn-block btn-lg text-decoration-none" %></div>
  </div>
  <p class='group--entname'>Transactions for <%= @group.name %></p>
  <div class='btn--div'>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-secondary btn-block btn-lg" %>
  </div>
</div>

<div id="entities">
  <p class='entities--total'>Total: $ <%= @group.total_amount %>.00</p>
  <% @entities.each do |entity| %>
    <div class='single--entity'>
      <p class='entity--name'><%= entity.name %></p>
      <p class='entity--amount'>$ <%= entity.amount %></p>
    </div>
  <% end %>
</div>

<div class='newentity--link'>
  <p class='newentity--paragraph'><%= link_to "Add New Transaction", new_group_entity_path(@group), class: 'nav-link' %></p>
</div>

app/views/entities/new.html.erb
<section class="vh-100 bg-image"
  style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-center mb-5">Create a new transaction</h2>


              <%= form_with model: @entity, url: group_entities_path(@group) do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>

                <div class="form-outline mb-4">
                  <%= f.text_field :name, placeholder: "Name of transaction", class: "form-control form-control-lg" %>
                </div>

                <div class="form-outline mb-4">
                  <%= f.number_field :amount, placeholder: "Amount", class: "form-control form-control-lg" %>
                </div>

                <div class="form-outline mb-4">
                  <p>Select Category</p>
                  <%= f.select :groups_id, @groups.map { |group| [group.name, group.id] }, {}, { class:'form-select'} %>
                </div>

                <div class="d-flex justify-content-center">
                  <%= f.submit "Create Transaction", class: "btn btn-success btn-block btn-lg gradient-custom-4 text-body" %>
                </div>

              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class='new--cart'>
  <h2 class='cartegory--title'>Categories</h2>
  <div class='btn--div'>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-secondary btn-block btn-lg" %>
  </div>
</div>

<div class='categories--index'>
  <div id="groups--list">
    <% @groups.each do |group| %>
      <div class='group--card'>
        <div class='group--details'>
          <div class='group--icon'>
            <%= image_tag group.icon, height: 50 %>
          </div>
          <p class='group--name'><%= group.name %></p>
          <p class='group--amount'>$ <%= group.total_amount %></p>
        </div>
        <p class='group--link'><%= link_to "See all #{group.name} transactions", group_entities_path(group_id: group.id) %></p>
        <p class='formatted--date'><%= group.created_at.strftime('%d %b %Y') %></p>
      </div>
    <% end %>
  </div>
</div>
<div class='newgroup--link'>
  <p class='newgroup--paragraph'><%= link_to "Add New Category", new_group_path, class: 'nav-link' %></p>
</div>

app/views/groups/new.html.erb
<div class='new--cart'>
  <div class='btn--div'>
    <div class='arrow--back'><%= link_to "<", groups_path, class: "btn btn-secondary btn-block btn-lg text-decoration-none" %></div>
  </div>
  <div class='btn--div'>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-secondary btn-block btn-lg"  %>
  </div>
</div>

<div class="mask d-flex align-items-center h-100 gradient-custom-3">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-9 col-lg-7 col-xl-6">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body p-5">
            <h2 class="text-center mb-5">Add a new Category</h2>

            <%= form_with model: @group, url: "/groups" do |f| %>

              <%= f.hidden_field :user_id, value: current_user.id %>

              <div class="form-outline mb-4">
                <%= f.text_field :name, placeholder: "Category Name", class: "form-control form-control-lg" %>
              </div>

              <div class="form-outline mb-4">
                <%= f.text_field :icon, placeholder: "Icon", class: "form-control form-control-lg" %>
              </div>

              <div class="d-flex justify-content-center">
                <%= f.submit "Save", class: "btn btn-success btn-block btn-lg gradient-custom-4 text-body" %>
              </div>

            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgeti</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash_screen/index.html.erb
<section class='splash--screen'>
  <h1>Budgeti</h1>

  <div class='splash--sign'>
    <p class='login--btn'><%= link_to "Login", new_user_session_path, class: 'nav-link';%></p>
    <p class='signup--btn'><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link'; %></p>
  </div>
</section>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>